[workspace]
members = [
  "crates/billing",
  "crates/test-data",
  "examples/rest",
  "examples/graphql",
  "examples/dynamodb",
  "examples/websocket",
  "examples/grpc",
  "benches/endpoint-benchmarks",
]
resolver = "2"
