[workspace]
members = [
  "crates/billing",
  "crates/test-data",
  "examples/rest",
  "examples/graphql",
  "examples/dynamodb",
  "examples/websocket",
]
resolver = "2"

[patch.crates-io]
this-rs = { path = "../this" }
