[package]
name = "test-data"
version = "0.1.0"
edition = "2021"

[dependencies]
billing = { path = "../billing" }
catalog = { path = "../catalog" }
inventory = { path = "../inventory" }
this-rs = "0.0.7"
anyhow = "1"
serde_json = "1"
